# Generated by Django 3.2.4 on 2021-06-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_prod_imgage_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_imgage_detail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
